### PR TITLE
Set version to 0.3.4

### PR DESCRIPTION
**Pull request by stuwilkins**

### CODE REVIEW

**Comment by stuwilkins** [comment]
Attn @mrakitin  and @stuartcampbell

**Review by mrakitin — APPROVED** [review]

**Comment by mrakitin** [comment]
Looks good. What explains the irregular tags (0.3.2 -> 0.3.4)?

**Comment by stuwilkins** [comment]
@mrakitin you mean missing a version? I think I perhaps somehow forgot to push the tag?

**Comment by mrakitin** [comment]
@stuwilkins, yes, I meant the missing version.

**Comment by stuwilkins** [comment]
OK, probably an error downstream of the keyboard

**Pull request merged**
